### ISSUE TITLE
Rubyslim doesn't work as documented in the README

### ISSUE THREAD

**Issue by caiofbpa** [unclebob/rubyslim#13]
If you follow the steps for usage defined in the README, all you're gonna get is "Cannot invoke constructor" error messages.

I had to dig into the mailing list and find a lone soul who solved the problem by cloning this repo and adapting the usage to mimic the old rubyslim, this way:

```
!define TEST_SYSTEM {slim}
!define TEST_RUNNER (../rubyslim/bin/rubyslim)
!define COMMAND_PATTERN {ruby -I %p %m}
!path your/ruby/fixtures
```

What's left for rubyslim to be ready to use out of the box? I'm interested in contributing but have no idea how to help.

**Comment by PQALAB** [comment]
Does Ruby Slim even work anymore? I cannot get it to run a test at all.

**Comment by reedlaw** [comment]
This setup works for me:

```
!define TEST_SYSTEM {slim}
!define TEST_RUNNER {${BUNDLER_ORIG_GEM_HOME}/bin/rubyslim}
!define COMMAND_PATTERN {ruby -C${PWD}/ -I %p %m}
!define SLIM_PORT {0}
!path ${PWD}/lib/fixtures
```

`BUNDLER_ORIG_GEM_HOME` is set by `bundle exec` but it doesn't work in our CI environment. Without the full path FitNesse has trouble finding `rubyslim`.
