### ISSUE TITLE
Ruby 1.9.x with rubyslim causing "require 'jcode'" error

### ISSUE THREAD

**Issue by leandromoreira** [unclebob/rubyslim#5]
Im trying to use your great tool on Ruby 1.9.x and it is causing this "error":
require 'jcode'
It seems not to be mandatory from ruby 1.9 and later. So I think it could be changed for
require 'jcode' if RUBY_VERSION < 1.9
But even changing every require jcode it raises another error:
'list_deserializer.rb:1:in `<': comparison of String with Float failed (ArgumentError)'. 
:^\

**Comment by dougbradbury** [comment]
the library has been updated to support 1.9.3
